array_fill (dopełnia numery w tabeli do danej wartości)
array_key_exists (sprawdza czy dany klucz jest w tabeli)
array_keys (funkcja używana do wypisania wszystkich kluczy z tabeli)
array_pop (wypisuje elementy tabeli, ale nie wypisuje ostatniej wartości tabeli)
array_push (powiększa tabele o dane wartości)
array_reverse (odwraca tabele)
array_search (wyszukuje daną wartość[szukanie igły w stogu siana])
array_slice (wyświetla)
array_unique (wyświetla tylko unikatowe wartości[jeśli jest ich wiele to wypisuje tylko ich pierwsze ])
array_values (wyświetla same wartości tabeli[NIE KLUCZE])

count (liczy wszystko w tabeli)
explode ()
in_array (wyszukuje daną rzecz w tabeli[KONKRETNEJ RZECZY])
is_array ()
range (TWORZY tabele Z WARTOŚCIAMI Z PODANEGO ZAKRESU)
list (TWORZY LISTE?)
shuffle (miesza w wartościach tabeli)

sort (sortuje od namniejszego klucza do największego?)
rsort (od namniejszej do najwiekszej)
asort (sortuje asoc tabele rosnąco)
ksort ()
arsort ()
krsort ()