console.log("Tekst")
console.log(404)
console.log(window)
console.table([1,2,3,"jeden","dwa","trzy"])
console.group('bulbulator')
console.log("losowy tekst")
console.log("kolejny losowy tekst")
console.log("jeszcze jeden losowy tekst")
console.groupEnd()